-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtZJ1SGQfmKWYLLNA
0VZFLLGvO+JihIe/LAL3Y3/lmFqgCgYIKoZIzj0DAQehRANCAAT3TAv3LSf40PR/
ZUehRQ8jabMsbOmogwh1gR3dwV7nGb/L4YotWsmPXnSuLv/6qkTlLyWcxmnobAid
3lfxfxtj
-----END PRIVATE KEY-----